<?php /* #?ini charset="utf-8"?

[ConnectorSettings]
AvailableConnectors[]=opendatadatasetfielddefinition
AvailableConnectors[]=opendatadatasetviewdefinition
AvailableConnectors[]=opendatadatasetimportfielddefinition
AvailableConnectors[]=opendatadataset
AvailableConnectors[]=opendatadatasetdelete
AvailableConnectors[]=opendatadatasetimport
AvailableConnectors[]=opendatadatasetdeleteitem
AvailableConnectors[]=opendatadatareset
AvailableConnectors[]=opendatadatasetselectspreadsheet
AvailableConnectors[]=opendatadatasetgoogleimport
AvailableConnectors[]=opendatadatasetimportgooglefields

[opendatadatasetfielddefinition_ConnectorSettings]
PHPClass=OpendataDatasetFieldDefinitionConnector

[opendatadatasetviewdefinition_ConnectorSettings]
PHPClass=OpendataDatasetViewDefinitionConnector

[opendatadatasetimportfielddefinition_ConnectorSettings]
PHPClass=OpendataDatasetImportCsvFieldsConnector

[opendatadataset_ConnectorSettings]
PHPClass=OpendataDatasetConnector

[opendatadatasetdelete_ConnectorSettings]
PHPClass=OpendataDatasetDeleteDataConnector

[opendatadatasetimport_ConnectorSettings]
PHPClass=OpendataDatasetImportCsvConnector

[opendatadatasetdeleteitem_ConnectorSettings]
PHPClass=OpendataDatasetDeleteItemConnector

[opendatadatareset_ConnectorSettings]
PHPClass=OpendataDatasetResetConnector

[opendatadatasetselectspreadsheet_ConnectorSettings]
PHPClass=OpendataDatasetSelectGoogleSpreadsheetConnector

[opendatadatasetgoogleimport_ConnectorSettings]
PHPClass=OpendataDatasetImportGoogleSpreadsheetConnector

[opendatadatasetimportgooglefields_ConnectorSettings]
PHPClass=OpendataDatasetImportGoogleSpreadsheetFieldsConnector


*/ ?>
